<a href="https://colab.research.google.com/github/Skattar/Binus-Projects/blob/main/BigData_SalesPredictCountry_PreprocessedScale_Classification_NaiveBayes_DecisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [190]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [191]:
dataset = pd.read_excel("Preprocessed_For_Classification_Sales.xlsx")
dataset.head()

Month       Age_Group Customer_Gender Product_Category Sub_Category  \
0  November     Youth (<25)               M      Accessories   Bike Racks   
1  November     Youth (<25)               M      Accessories   Bike Racks   
2     March  Adults (35-64)               M      Accessories   Bike Racks   
3     March  Adults (35-64)               M      Accessories   Bike Racks   
4       May  Adults (35-64)               F      Accessories   Bike Racks   

               Product  Order_Quantity    Country  
0  Hitch Rack - 4-Bike               8     Canada  
1  Hitch Rack - 4-Bike               8     Canada  
2  Hitch Rack - 4-Bike              23  Australia  
3  Hitch Rack - 4-Bike              20  Australia  
4  Hitch Rack - 4-Bike               4  Australia

In [192]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113036 entries, 0 to 113035
Data columns (total 8 columns):
 #   Column            Non-Null Count   Dtype 
---  ------            --------------   ----- 
 0   Month             113036 non-null  object
 1   Age_Group         113036 non-null  object
 2   Customer_Gender   113036 non-null  object
 3   Product_Category  113036 non-null  object
 4   Sub_Category      113036 non-null  object
 5   Product           113036 non-null  object
 6   Order_Quantity    113036 non-null  int64 
 7   Country           113036 non-null  object
dtypes: int64(1), object(7)
memory usage: 6.9+ MB


In [193]:
dataset.empty

False

In [194]:
en = LabelEncoder()
dataset['Country'] = en.fit_transform(dataset['Country'])
dataset['Product'] = en.fit_transform(dataset['Product'])
dataset['Sub_Category'] = en.fit_transform(dataset['Sub_Category'])
dataset['Product_Category'] = en.fit_transform(dataset['Product_Category'])
dataset['Customer_Gender'] = en.fit_transform(dataset['Customer_Gender'])
dataset['Age_Group'] =en.fit_transform(dataset['Age_Group'])
dataset['Month'] = en.fit_transform(dataset['Month'])
dataset.head()

Month  Age_Group  Customer_Gender  Product_Category  Sub_Category  Product  \
0      9          3                1                 0             0       12   
1      9          3                1                 0             0       12   
2      7          0                1                 0             0       12   
3      7          0                1                 0             0       12   
4      8          0                0                 0             0       12   

   Order_Quantity  Country  
0               8        1  
1               8        1  
2              23        0  
3              20        0  
4               4        0

In [195]:
x = dataset.iloc[:, :-1].values #6 Labels other than Country
y = dataset.iloc[:, -1].values #Country

In [196]:
x

array([[ 9,  3,  1, ...,  0, 12,  8],
       [ 9,  3,  1, ...,  0, 12,  8],
       [ 7,  0,  1, ...,  0, 12, 23],
       ...,
       [ 0,  3,  1, ..., 16,  4, 22],
       [ 7,  0,  0, ..., 16,  3, 24],
       [ 7,  0,  0, ..., 16,  3, 23]])

In [197]:
y

array([1, 1, 0, ..., 0, 2, 2])

In [198]:
x_train,x_test,y_train,y_test = train_test_split(x, y, test_size=0.1, random_state=123) #data yg di test 20%
print("x_train = ", len(x_train))
print("x_test = ", len(x_test))
print("y_train = ", len(y_train))
print("y_test = ", len(y_test))


x_train =  101732
x_test =  11304
y_train =  101732
y_test =  11304


In [199]:
sc = StandardScaler() #dataset need to be scaled to have normalized data for all and no bias outlier
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [200]:
x_train

array([[ 1.34381474,  1.53127123, -1.03190493, ..., -1.62707856,
        -0.90135554,  1.57900404],
       [-1.00155999,  1.53127123, -1.03190493, ...,  1.03015876,
        -1.07116892, -0.51283215],
       [-1.00155999, -0.96886441,  0.96908152, ..., -1.62707856,
         1.62158609,  1.68359585],
       ...,
       [ 0.17112738, -0.96886441, -1.03190493, ..., -1.40564211,
        -1.43505473,  0.32390232],
       [ 0.46429922,  0.69789268,  0.96908152, ..., -0.74133278,
        -1.19246419,  1.05604499],
       [-0.70838815,  1.53127123, -1.03190493, ..., -1.62707856,
        -0.10080675,  1.1606368 ]])

In [201]:
x_test

array([[ 0.75747106,  0.69789268, -1.03190493, ...,  0.14441299,
        -0.61024689, -1.14038301],
       [-0.41521631,  1.53127123, -1.03190493, ...,  1.03015876,
        -0.17358391, -1.0357912 ],
       [-0.12204446, -0.96886441,  0.96908152, ..., -1.62707856,
         1.62158609,  0.0101269 ],
       ...,
       [ 1.0506429 , -0.96886441,  0.96908152, ...,  1.03015876,
        -0.17358391, -0.51283215],
       [ 0.17112738,  1.53127123,  0.96908152, ...,  1.03015876,
        -0.17358391, -0.09446491],
       [-1.00155999,  1.53127123, -1.03190493, ..., -1.62707856,
         1.62158609,  0.53308594]])

In [202]:
y_train

array([1, 5, 5, ..., 1, 5, 0])

In [203]:
y_test

array([4, 0, 5, ..., 5, 3, 4])

In [204]:
classifier = GaussianNB()
classifier.fit(x_train,y_train) # trained data is whats gonna be tested

GaussianNB()

In [205]:
y_pred = classifier.predict(x_test)
y_pred

array([5, 0, 5, ..., 5, 5, 5])

In [206]:
classifier.predict_proba(x_test)

array([[0.28174041, 0.08124731, 0.10539572, 0.1170474 , 0.12160169,
        0.29296748],
       [0.2751124 , 0.09566545, 0.12489213, 0.1220863 , 0.12161222,
        0.26063149],
       [0.15245715, 0.12834391, 0.07996838, 0.09133242, 0.13595275,
        0.41194539],
       ...,
       [0.20402908, 0.12581454, 0.08833471, 0.0868517 , 0.11872927,
        0.3762407 ],
       [0.26114343, 0.13013943, 0.11101169, 0.10742606, 0.11585509,
        0.27442429],
       [0.19731707, 0.12692116, 0.11013711, 0.12001043, 0.13894386,
        0.30667036]])

**Evaluation Phase**

In [207]:
cm = confusion_matrix(y_test,y_pred)
print(cm)

[[ 227    0    0    0    0 2187]
 [  73    0    0    0    0 1415]
 [  75    0    0    0    0  987]
 [  78    0    0    0    0 1011]
 [ 109    0    0    0    0 1251]
 [ 169    0    0    0    0 3722]]


In [208]:
accuracy = classification_report(y_test,y_pred)
print(accuracy)

              precision    recall  f1-score   support

           0       0.31      0.09      0.14      2414
           1       0.00      0.00      0.00      1488
           2       0.00      0.00      0.00      1062
           3       0.00      0.00      0.00      1089
           4       0.00      0.00      0.00      1360
           5       0.35      0.96      0.51      3891

    accuracy                           0.35     11304
   macro avg       0.11      0.18      0.11     11304
weighted avg       0.19      0.35      0.21     11304



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [209]:
accuracy = accuracy_score(y_test,y_pred)
print("Accuracy: %d percent"%(accuracy*100))

Accuracy: 34 percent


Manual Comparison between tested y against predicted trained y

In [210]:
ydata = pd.DataFrame()
ydata['y_test'] = pd.DataFrame(y_test)
ydata['y_pred'] = pd.DataFrame(y_pred)
ydata

y_test  y_pred
0           4       5
1           0       0
2           5       5
3           0       5
4           1       5
...       ...     ...
11299       5       5
11300       0       5
11301       5       5
11302       3       5
11303       4       5

[11304 rows x 2 columns]

In [211]:
ydata.to_excel('actual_dat_prediction.xlsx', index=False)

In [212]:
### Deicison tree algorithm

DECISION TREE ALGORITHM

In [213]:
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [214]:
Y_pred = dt.predict(x_test)

In [215]:
accuracy = accuracy_score(y_test,Y_pred)
print("Accuracy: %d percent"%(accuracy*100))

Accuracy: 41 percent


In [216]:
accuracy = classification_report(y_test,Y_pred)
print('Classification Report:',accuracy)

Classification Report:               precision    recall  f1-score   support

           0       0.39      0.49      0.43      2414
           1       0.35      0.35      0.35      1488
           2       0.30      0.27      0.29      1062
           3       0.33      0.29      0.31      1089
           4       0.38      0.32      0.34      1360
           5       0.53      0.50      0.52      3891

    accuracy                           0.42     11304
   macro avg       0.38      0.37      0.37     11304
weighted avg       0.42      0.42      0.41     11304



In [217]:
cm = confusion_matrix(y_test,Y_pred)
print(cm)

[[1175  217  155  139  181  547]
 [ 316  524   79   77   99  393]
 [ 255   88  292   85   92  250]
 [ 220  113   98  316   87  255]
 [ 281  122  109  110  432  306]
 [ 765  445  245  218  261 1957]]
